module.exports = {
    MOVE_SHIP: "MOVE_SHIP",
    ROTATE_SHIP: "ROTATE_SHIP",
    GUESS: "GUESS",
    ENEMY_GUESS: "ENEMY_GUESS",
    REGISTER_FOR_TEAM: "REGISTER_FOR_TEAM",
    TEAM_READY: "TEAM_READY",
    GET_STATE: "GET_STATE",
    REGISTERED: "REGISTERED",
    REGISTER_FAILED: "REGISTER_FAILED",
    STATE_CHANGE: "STATE_CHANGE",
    SELECT_BLOCK: "SELECT_BLOCK",
    GAME_ENDED: "GAME_ENDED",
    CHANGE_NAMES: "CHANGE_NAMES"
}