module.exports = {
    "Destroyer": {
        name: "Destroyer",
        x: 0,
        y: 5,
        length: 3,
        rotation: 90,
        sunk: false,
    },
    "Carrier": {
        name: "Carrier",
        x: 0,
        y: 0,
        length: 5,
        rotation: 90,
        sunk: false,
        hasOffset: true,
    },
    "Battleship": {
        name: "Battleship",
        x: 0,
        y: 1,
        length: 5,
        rotation: 90,
        sunk: false,
    },
    "Cruiser": {
        name: "Cruiser",
        x: 0,
        y: 2,
        length: 4,
        rotation: 90,
        sunk: false,
    },
    "Cruiser 2": {
        name: "Cruiser",
        x: 0,
        y: 3,
        length: 4,
        rotation: 90,
        sunk: false,
    },
    "Submarine": {
        name: "Submarine",
        x: 0,
        y: 4,
        length: 3,
        rotation: 90,
        sunk: false,
    },
    "Submarine 2": {
        name: "Submarine",
        x: 0,
        y: 6,
        length: 3,
        rotation: 90,
        sunk: false,
    },
}


// "Patrol Boat": {
//     name: "Patrol Boat",
//     x: 0,
//     y: 0,
//     length: 2,
//     rotation: 90,
//     sunk: false,
// },
